project:
  type: website
engine: jupyter
website:
  title: "Lin511-2024"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
  sidebar: 
    contents:
      - syllabus.qmd


format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

