project:
  type: website

license: CC-BY-SA 4.0
website:
  title: "Lin511-2024"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
  sidebar: 
    contents:
      - href: syllabus.qmd
        text: Syllabus

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    fontsize: large

editor: visual

