project:
  type: website

license: CC-BY-SA 4.0
website:
  title: "Lin511-2024"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Notes"
        href: notes/index.qmd
  sidebar: 
    - title: "Home"
      contents:
        - text: Home
          href: index.qmd
        - href: syllabus/syllabus.qmd
          text: Syllabus
        - href: syllabus/schedule.qmd
          text: Schedule
    - title: "Notes"
      contents:
        - text: Notes Home
          href: notes/index.qmd
        - section: Class Meetings
          contents: 
            - auto: notes/meetings/*
    # contents:
    #   - href: syllabus.qmd
    #     text: Syllabus

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    fontsize: large

editor: visual

