project:
  type: website

license: CC-BY-SA 4.0
author: 
  name: Josef Fruehwald
  url: https://jofrhwld.github.io/
execute: 
  freeze: auto

citation:
  container-title: "Lin511 2024: Computational Linguistics"

website:
  title: "Lin511-2024"
  favicon: assets/logo.svg
  site-url: https://lin511-2024.github.io
  repo-url: https://github.com/Lin511-2024/Lin511-2024.github.io
  repo-actions: source
  open-graph: true
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Notes"
        href: notes/index.qmd
      - text: "About"
        href: about.qmd
    right:
      - icon: github
        href: https://github.com/Lin511-2024
  sidebar: 
    - title: "Home"
      logo: assets/logo.svg
      contents:
        - text: Home
          href: index.qmd
        - href: syllabus/syllabus.qmd
          text: Syllabus
        - href: syllabus/schedule.qmd
          text: Schedule
    - title: "Notes"
      contents:
        - text: Notes Home
          href: notes/index.qmd
        - section: Concepts
          contents:
            - auto: notes/concepts/*
        - section: Class Meetings
          contents: 
            - auto: notes/meetings/*
        - section: Programming
          contents: 
            - auto: notes/programming/*
        - section: In-class
          contents: 
            - auto: notes/in_class/*        
    # contents:
    #   - href: syllabus.qmd
    #     text: Syllabus

format:
  html:
    theme:
      light: flatly
      dark: [darkly, styles/dark.scss]
    css: styles/styles.css
    toc: true
    toc-depth: 4
    fontsize: large
    smooth-scroll: true
    fig-cap-location: margin
    citation: true
    highlight-style: github

date-modified: last-modified

editor: visual

